# Generated by Django 5.2.5 on 2025-09-06 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_remove_task_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'Todo'), ('in-progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], db_index=True, default='to-do', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
